#! /usr/bin/env bash

set -e
ACCOUNT="${1:?Usage: pull-from-imap-server <account>}"
TIMESTAMP=~/.maildir/timestamp
CHECK_POSTPONED_TIMESTAMP=$(mktemp /tmp/check-postponed-XXXXXX)
date +%s > "$CHECK_POSTPONED_TIMESTAMP"

mbsync-and-decrypt; notmuch new; sleep 20;
rpasswd > $TIMESTAMP

while true; do
    date +[%H:%M:%S]
    pause-imap-sync --from "$ACCOUNT";
    mbsync-and-decrypt; notmuch new; sleep 5
    rpasswd > $TIMESTAMP
    [ $((RANDOM % 1000)) -lt 3 ] && ai-train || sleep 5
    [ $(( $(date +%s) - $(cat "$CHECK_POSTPONED_TIMESTAMP") )) -ge 3600 ] \
        && { check-postponed; date +%s > "$CHECK_POSTPONED_TIMESTAMP"; } \
        || sleep 5
done
